name: test-conda-env-py3-macos
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs
  - cgen
  - clangdev
  - cmake
  - colorama
  - cython
  - dealii
  - genpy
  - git
  - h5py
  - iniconfig
  - islpy
  - numpy
  - openmp
  - packaging
  - pluggy
  - pocl
  - py
  - pybind11
  - pyevtk
  - pyfmmlib
  - pyopencl
  - pyrsistent
  - pytest
  - pytest-cov
  - python-symengine
  - python=3
  - pyvkfft
  - scipy
  - symengine
  - sympy
  - toml

  - pip
  - pip:
    - git+https://gitlab.tiker.net/inducer/loopy
    - git+https://gitlab.tiker.net/inducer/gmsh_interop
    - git+https://gitlab.tiker.net/inducer/boxtree
    - git+https://gitlab.tiker.net/inducer/modepy
    - git+https://gitlab.tiker.net/inducer/arraycontext
    - git+https://gitlab.tiker.net/inducer/meshmode
    - git+https://gitlab.tiker.net/inducer/pymbolic
    - git+https://gitlab.tiker.net/inducer/sumpy
    - git+https://gitlab.tiker.net/inducer/pytential
