name: test-conda-env-py3-macos
channels:
  - conda-forge
  - nodefaults
dependencies:
  - attrs
  - cgen
  - clangdev
  - cmake
  - colorama
  - cython
  - genpy
  - git
  - iniconfig
  - islpy
  - numpy
  - llvm-openmp
  - packaging
  - pluggy
  - pocl
  - pyfmmlib
  - pyopencl
  - pyrsistent
  - pytest
  - pytest-cov
  - python-symengine
  - python=3.11
  - pyvkfft
  - scipy
  - symengine
  - sympy
  - pip
  - uv
