__copyright__ = "Copyright (C) 2017 - 2018 Xiaoyu Wei"

__license__ = """
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""

__doc__ = """Expansion wranglers implementing the ``fpnd`` strategy.

``fpnd`` means: the **f**\\ ar field is handled by a **p**\\ article
approximation (a plain FMM over the quadrature nodes), while the **n**\\ ear
field is evaluated **d**\\ irectly from precomputed interaction tables.

Two backends provide the far field:

* :mod:`volumential.wranglers.sumpy_backend` -- expansions generated by
  :mod:`sumpy`, works for every kernel sumpy can differentiate, and carries the
  Helmholtz near-field split.
* :mod:`volumential.wranglers.fmmlib_backend` -- expansions from
  :mod:`pyfmmlib` via :mod:`boxtree.pyfmmlib_integration`, restricted to 2D/3D
  Laplace and Helmholtz but considerably faster.

The remaining modules are the pieces both backends share: near-field table
marshalling (:mod:`~volumential.wranglers.table_data`), the symmetry-orbit
reconstruction used to keep reduced tables small
(:mod:`~volumential.wranglers.arithmetic_orbits`,
:mod:`~volumential.wranglers.orbit_generated`), and assorted device-array,
kernel-introspection and layout-validation helpers.

:mod:`volumential.expansion_wrangler_fpnd` remains importable and re-exports
every name this package defines.
"""

from volumential.wranglers.device_arrays import inverse_id_map, level_to_rscale
from volumential.wranglers.fmmlib_backend import (
    FPNDFMMLibExpansionWrangler,
    FPNDFMMLibTreeIndependentDataForWrangler,
)
from volumential.wranglers.fmmlib_batched import FMMLibBatchedStagesMixin
from volumential.wranglers.helmholtz_split import HelmholtzSplitCorrectionMixin
from volumential.wranglers.nearfield_cache import NearFieldPayloadCacheMixin
from volumential.wranglers.split_terms import HelmholtzSplitCacheAccounting
from volumential.wranglers.sumpy_backend import (
    FPNDExpansionWrangler,
    FPNDSumpyExpansionWrangler,
    FPNDSumpyTreeIndependentDataForWrangler,
    FPNDTreeIndependentDataForWrangler,
)
from volumential.wranglers.timing import SumpyTimingFuture


__all__ = [
    "FMMLibBatchedStagesMixin",
    "FPNDExpansionWrangler",
    "FPNDFMMLibExpansionWrangler",
    "FPNDFMMLibTreeIndependentDataForWrangler",
    "FPNDSumpyExpansionWrangler",
    "FPNDSumpyTreeIndependentDataForWrangler",
    "FPNDTreeIndependentDataForWrangler",
    "HelmholtzSplitCacheAccounting",
    "HelmholtzSplitCorrectionMixin",
    "NearFieldPayloadCacheMixin",
    "SumpyTimingFuture",
    "inverse_id_map",
    "level_to_rscale",
]

# vim: filetype=pyopencl:foldmethod=marker
